import { defineConfig } from 'eslint/config';
import eslintConfigPrettier from 'eslint-config-prettier/flat';

import idMatch from './src/index.js';

export default defineConfig([
  {
    files: ['**/*.{js,mjs,cjs}'],
    plugins: { 'id-match': idMatch },
    rules: {
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'warn',
      'getter-return': 'error',
      'no-async-promise-executor': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['warn', 'always'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': ['warn', { checkRelationalComparisons: true }],
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'warn',
      'no-duplicate-imports': 'warn',
      'no-empty-character-class': 'warn',
      'no-empty-pattern': 'warn',
      'no-ex-assign': 'error',
      'no-fallthrough': 'warn',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': ['error', 'both', { blockScopedFunctions: 'disallow' }],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': [
        'error',
        {
          skipComments: false,
          skipJSXText: false,
        },
      ],
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'error',
      'no-prototype-builtins': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'warn',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': [
        'warn',
        {
          varsIgnorePattern: '^_',
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          reportUsedIgnorePattern: true,
        },
      ],
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'no-useless-backreference': 'error',
      'require-atomic-updates': 'warn',
      'use-isnan': [
        'error',
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],

      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      'class-methods-use-this': [
        'warn',
        {
          enforceForClassFields: false,
          ignoreOverrideMethods: true,
          ignoreClassesWithImplements: 'all',
        },
      ],
      'consistent-return': 'error',
      curly: ['error', 'all'],
      'default-case': 'warn',
      'default-case-last': 'warn',
      'dot-notation': 'warn',
      eqeqeq: ['error', 'always'],
      'func-name-matching': [
        'error',
        {
          considerPropertyDescriptor: true,
          includeCommonJSModuleExports: true,
        },
      ],
      'func-names': 'error',
      'func-style': 'error',
      'grouped-accessor-pairs': ['error', 'anyOrder', { enforceForTSTypes: true }],
      'logical-assignment-operators': ['warn', 'always', { enforceForIfStatements: true }],
      'new-cap': 'warn',
      'no-alert': 'error',
      'no-array-constructor': 'warn',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-console': 'error',
      'no-delete-var': 'error',
      'no-else-return': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-static-block': 'warn',
      'no-eq-null': 'error',
      'no-eval': 'warn',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-extra-label': 'warn',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': ['error', { lexicalBindings: false }],
      'no-implied-eval': 'warn',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'error',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'error',
      'no-plusplus': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'warn',
      'no-throw-literal': 'error',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-labels': 'warn',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'object-shorthand': 'warn',
      'one-var': ['error', 'never'],
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'warn',
      'prefer-numeric-literals': 'warn',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'preserve-caught-error': 'warn',
      'require-await': 'warn',
      'require-unicode-regexp': ['error', { requireFlag: 'u' }],
      'require-yield': 'warn',
      strict: 'error',
      'symbol-description': 'warn',
      'vars-on-top': 'error',
      yoda: ['warn', 'never', { exceptRange: true }],

      'id-match/imports-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/vars-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/functions-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/properties-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/classes-match': ['warn', '^(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/members-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/parameters-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/exports-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
    },
  },
  eslintConfigPrettier,
]);
