import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier/flat';

import idMatch from './dist/index.js';

export default defineConfig([
  {
    ignores: ['dist/**'],
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    plugins: { 'id-match': idMatch },
    rules: {
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'warn',
      'getter-return': 'error',
      'no-async-promise-executor': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['warn', 'always'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': ['warn', { checkRelationalComparisons: true }],
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'warn',
      'no-duplicate-imports': 'warn',
      'no-empty-character-class': 'warn',
      'no-empty-pattern': 'warn',
      'no-ex-assign': 'error',
      'no-fallthrough': 'warn',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': ['error', 'both', { blockScopedFunctions: 'disallow' }],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': [
        'error',
        {
          skipComments: false,
          skipJSXText: false,
        },
      ],
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'error',
      'no-prototype-builtins': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'warn',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': [
        'warn',
        {
          varsIgnorePattern: '^_',
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          reportUsedIgnorePattern: true,
        },
      ],
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'no-useless-backreference': 'error',
      'require-atomic-updates': 'warn',
      'use-isnan': [
        'error',
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],

      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      'class-methods-use-this': [
        'warn',
        {
          enforceForClassFields: false,
          ignoreOverrideMethods: true,
          ignoreClassesWithImplements: 'all',
        },
      ],
      'consistent-return': 'error',
      curly: ['error', 'all'],
      'default-case': 'warn',
      'default-case-last': 'warn',
      'dot-notation': 'warn',
      eqeqeq: ['error', 'always'],
      'func-name-matching': [
        'error',
        {
          considerPropertyDescriptor: true,
          includeCommonJSModuleExports: true,
        },
      ],
      'func-names': 'error',
      'func-style': 'error',
      'grouped-accessor-pairs': ['error', 'anyOrder', { enforceForTSTypes: true }],
      'logical-assignment-operators': ['warn', 'always', { enforceForIfStatements: true }],
      'no-alert': 'error',
      'no-array-constructor': 'warn',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-console': 'error',
      'no-delete-var': 'error',
      'no-else-return': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-static-block': 'warn',
      'no-eq-null': 'error',
      'no-eval': 'warn',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-extra-label': 'warn',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': ['error', { lexicalBindings: false }],
      'no-implied-eval': 'warn',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'error',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'error',
      'no-plusplus': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'warn',
      'no-throw-literal': 'error',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-labels': 'warn',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'object-shorthand': 'warn',
      'one-var': ['error', 'never'],
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'warn',
      'prefer-numeric-literals': 'warn',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'preserve-caught-error': 'warn',
      'require-await': 'warn',
      'require-unicode-regexp': ['error', { requireFlag: 'u' }],
      'require-yield': 'warn',
      strict: 'error',
      'symbol-description': 'warn',
      'vars-on-top': 'error',
      yoda: ['warn', 'never', { exceptRange: true }],

      'id-match/imports-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/vars-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/functions-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/properties-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/classes-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/members-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/parameters-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/exports-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
    },
  },
  {
    files: ['**/*.{ts,mts,cts}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'id-match': idMatch,
    },
    rules: {
      'array-callback-return': 'error',
      'constructor-super': 'error',
      'for-direction': 'warn',
      'getter-return': 'error',
      'no-async-promise-executor': 'warn',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['warn', 'always'],
      'no-const-assign': 'error',
      'no-constant-binary-expression': ['warn', { checkRelationalComparisons: true }],
      'no-constant-condition': 'warn',
      'no-constructor-return': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      // '@typescript-eslint/no-dupe-class-members': 'error',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'warn',
      'no-duplicate-imports': 'warn',
      'no-empty-character-class': 'warn',
      'no-empty-pattern': 'warn',
      'no-ex-assign': 'error',
      'no-fallthrough': 'warn',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': ['error', 'both', { blockScopedFunctions: 'disallow' }],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': [
        'error',
        {
          skipComments: false,
          skipJSXText: false,
        },
      ],
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'error',
      'no-prototype-builtins': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'warn',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'warn',
      'no-unsafe-optional-chaining': 'error',
      '@typescript-eslint/no-unused-private-class-members': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          varsIgnorePattern: '^_',
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          reportUsedIgnorePattern: true,
        },
      ],
      '@typescript-eslint/no-use-before-define': ['error', { ignoreTypeReferences: false }],
      'no-useless-assignment': 'warn',
      'no-useless-backreference': 'error',
      'require-atomic-updates': 'warn',
      'use-isnan': [
        'error',
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],

      'arrow-body-style': ['error', 'as-needed'],
      'block-scoped-var': 'error',
      '@typescript-eslint/class-methods-use-this': [
        'warn',
        {
          enforceForClassFields: false,
          ignoreOverrideMethods: true,
          ignoreClassesThatImplementAnInterface: true,
        },
      ],
      // '@typescript-eslint/consistent-return': 'error',
      curly: ['error', 'all'],
      'default-case': 'warn',
      'default-case-last': 'warn',
      '@typescript-eslint/dot-notation': ['warn', { allowIndexSignaturePropertyAccess: true }],
      eqeqeq: ['error', 'always'],
      'func-name-matching': [
        'error',
        {
          considerPropertyDescriptor: true,
          includeCommonJSModuleExports: true,
        },
      ],
      'func-names': 'error',
      'func-style': 'error',
      'grouped-accessor-pairs': ['error', 'anyOrder', { enforceForTSTypes: true }],
      'logical-assignment-operators': ['warn', 'always', { enforceForIfStatements: true }],
      'no-alert': 'error',
      '@typescript-eslint/no-array-constructor': 'warn',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-console': 'error',
      'no-delete-var': 'error',
      'no-else-return': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-static-block': 'warn',
      'no-eq-null': 'error',
      'no-eval': 'warn',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-extra-label': 'warn',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': ['error', { lexicalBindings: false }],
      '@typescript-eslint/no-implied-eval': 'warn',
      '@typescript-eslint/no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'error',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'error',
      'no-plusplus': 'error',
      'no-proto': 'error',
      // '@typescript-eslint/no-redeclare': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'warn',
      'no-throw-literal': 'error',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      'no-unused-labels': 'warn',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      '@typescript-eslint/no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'object-shorthand': 'warn',
      'one-var': ['error', 'never'],
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      '@typescript-eslint/prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'warn',
      'prefer-numeric-literals': 'warn',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'warn',
      '@typescript-eslint/prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'preserve-caught-error': 'warn',
      '@typescript-eslint/require-await': 'warn',
      'require-unicode-regexp': ['error', { requireFlag: 'u' }],
      'require-yield': 'warn',
      strict: 'error',
      'symbol-description': 'warn',
      'vars-on-top': 'error',
      yoda: ['warn', 'never', { exceptRange: true }],

      '@typescript-eslint/adjacent-overload-signatures': 'warn',
      '@typescript-eslint/array-type': ['warn', { default: 'array' }],
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/consistent-generic-constructors': 'warn',
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          objectLiteralTypeAssertions: 'never',
          arrayLiteralTypeAssertions: 'never',
        },
      ],
      '@typescript-eslint/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/method-signature-style': 'error',
      '@typescript-eslint/no-array-delete': 'error',
      '@typescript-eslint/no-base-to-string': 'error',
      '@typescript-eslint/no-confusing-non-null-assertion': 'warn',
      '@typescript-eslint/no-confusing-void-expression': ['error', { ignoreVoidOperator: true }],
      '@typescript-eslint/no-deprecated': 'warn',
      '@typescript-eslint/no-duplicate-enum-values': 'warn',
      '@typescript-eslint/no-empty-object-type': [
        'error',
        {
          allowInterfaces: 'always',
          allowObjectTypes: 'always',
        },
      ],
      '@typescript-eslint/no-extra-non-null-assertion': 'warn',
      '@typescript-eslint/no-extraneous-class': 'warn',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      '@typescript-eslint/no-inferrable-types': 'warn',
      '@typescript-eslint/no-invalid-void-type': 'error',
      '@typescript-eslint/no-meaningless-void-operator': ['warn', { checkNever: true }],
      '@typescript-eslint/no-misused-new': 'warn',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-misused-spread': 'error',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
      '@typescript-eslint/no-require-imports': 'error',
      '@typescript-eslint/no-this-alias': 'warn',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
      '@typescript-eslint/no-unnecessary-condition': [
        'warn',
        {
          allowConstantLoopConditions: 'always',
          checkTypePredicates: true,
        },
      ],
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'warn',
      '@typescript-eslint/no-unnecessary-qualifier': 'warn',
      '@typescript-eslint/no-unnecessary-template-expression': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/no-unnecessary-type-constraint': 'warn',
      '@typescript-eslint/no-unnecessary-type-conversion': 'warn',
      // '@typescript-eslint/no-unnecessary-type-parameters': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
      '@typescript-eslint/no-useless-default-assignment': 'warn',
      '@typescript-eslint/no-useless-empty-export': 'warn',
      '@typescript-eslint/no-wrapper-object-types': 'error',
      '@typescript-eslint/non-nullable-type-assertion-style': 'warn',
      '@typescript-eslint/parameter-properties': ['warn', { prefer: 'parameter-property' }],
      '@typescript-eslint/prefer-as-const': 'warn',
      '@typescript-eslint/prefer-find': 'warn',
      '@typescript-eslint/prefer-for-of': 'warn',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-includes': 'warn',
      '@typescript-eslint/prefer-literal-enum-member': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      '@typescript-eslint/prefer-nullish-coalescing': 'warn',
      '@typescript-eslint/prefer-readonly': 'warn',
      '@typescript-eslint/prefer-reduce-type-parameter': 'warn',
      '@typescript-eslint/prefer-regexp-exec': 'warn',
      '@typescript-eslint/prefer-return-this-type': 'warn',
      '@typescript-eslint/prefer-string-starts-ends-with': 'warn',
      '@typescript-eslint/related-getter-setter-pairs': 'warn',
      '@typescript-eslint/require-array-sort-compare': 'error',
      '@typescript-eslint/restrict-plus-operands': 'error',
      '@typescript-eslint/return-await': ['error', 'always'],
      '@typescript-eslint/strict-boolean-expressions': 'error',
      '@typescript-eslint/strict-void-return': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': ['warn', { requireDefaultForNonUnion: true }],
      '@typescript-eslint/triple-slash-reference': [
        'error',
        {
          lib: 'never',
          types: 'never',
        },
      ],
      '@typescript-eslint/unbound-method': 'error',

      'id-match/imports-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/vars-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/functions-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/properties-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/classes-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/interfaces-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/members-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/type-aliases-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/enumerations-match': ['warn', '^_?(?:[A-Z][a-z]*)(?:[A-Z][a-z]*|\\d+)*$'],
      'id-match/parameters-match': ['warn', '^_?(?:(?:[a-z]+|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
      'id-match/exports-match': ['warn', '^_?(?:(?:[A-Za-z][a-z]*|\\d+)(?:[A-Z][a-z]*|\\d+)*)?$'],
    },
  },
  eslintConfigPrettier,
]);
